version: '3.1'

services:

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - "./sql_scripts/:/home"
    environment:
      MYSQL_ROOT_PASSWORD: "tema_e"
      MYSQL_DATABASE: "eleicoes"

  metabase:
    image: metabase/metabase
    ports:
      - "3000:3000"
    volumes:
      - "./metabase-data:/metabase-data"
    environment:
      MB_DB_FILE: "/metabase-data/metabase.db"
      MB_DB_TYPE: "mysql"
      MB_DB_DBNAME: "eleicoes"
      MB_DB_PORT: "3306"
      MB_DB_USER: "root"
      MB_DB_PASS: "tema_e"
      MB_DB_HOST: "db"
    depends_on:
      - db
