version: '3.1'

services:

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - "./sql_scripts/:/home"
    environment:
      MYSQL_ROOT_PASSWORD: "tema_e"
      MYSQL_DATABASE: "eleicoes"

  grafana:
    image: grafana/grafana:5.1.0
    command: bash -c "./wait-for-it.sh db:3306 --timeout=120 --strict -- sleep 14 && echo DB Ready"
    ports:
      - "3000:3000"
    environment:
      GF_DATABASE_TYPE: "mysql"
      GF_DATABASE_HOST: "db:3306"
      GF_DATABASE_NAME: "eleicoes"
      GF_DATABASE_USER: "root"
      GF_DATABASE_PASSWORD: "tema_e"
    depends_on:
      - db
    user: "104"
