/* fisico eleições: */

CREATE DATABASE IF NOT EXISTS eleicoes;

USE eleicoes;

CREATE TABLE CANDIDATO (
    cpf VARCHAR(15) NOT NULL,
    nomeUrna VARCHAR(100),
    sexo enum('FEMININO', 'MASCULINO'),
    nomeCandidato VARCHAR(15) NOT NULL,
    dtNascimento DATE,

    CONSTRAINT CANDIDATO_PK PRIMARY KEY (cpf)
);

CREATE TABLE CARGO (
    idCargo INT NOT NULL,
    descricaoCargo VARCHAR(100) NOT NULL,

    CONSTRAINT CARGO_PK PRIMARY KEY (idCargo)
);

CREATE TABLE SITUACAO (
    idSituacao INT NOT NULL,
    descricaoSituacao VARCHAR(50) NOT NULL,

    CONSTRAINT SITUACAO_PK PRIMARY KEY (idSituacao)
);

CREATE TABLE PARTIDO (
    sigla VARCHAR(15) NOT NULL,
    nomePartido VARCHAR(50),

    CONSTRAINT PARTIDO_PK PRIMARY KEY (sigla)
);

CREATE TABLE CANDIDATURA (
    cpf VARCHAR(15) NOT NULL,
    ano DATE NOT NULL,
    -- numeroCandidato INT NOT NULL,
    unidadeEleitoral VARCHAR(100) NOT NULL,
    unidadeFederativa CHAR(2) NOT NULL,
    idCargo INT NOT NULL,
    idSituacao INT NOT NULL,
    sigla VARCHAR(15) NOT NULL,

    -- TODO conferir aqui
    CONSTRAINT CANDIDATURA_CANDIDATO_FK FOREIGN KEY (cpf) REFERENCES CANDIDATO (cpf),
    CONSTRAINT CANDIDATURA_PK PRIMARY KEY (ano, cpf),
    CONSTRAINT CANDIDATURA_CARGO_FK FOREIGN KEY (idCargo) REFERENCES CARGO (idCargo),
    CONSTRAINT CANDIDATURA_SITUACAO_FK FOREIGN KEY (idSituacao) REFERENCES SITUACAO (idSituacao),
    CONSTRAINT CANDIDATURA_SIGLA_FK FOREIGN KEY (sigla) REFERENCES PARTIDO (sigla)
);

CREATE TABLE TIPOPATRIMONIO (
    idTipoPatrimonio INT NOT NULL,
    descricaoTipoPatrimonio VARCHAR(100) NOT NULL,

    CONSTRAINT TIPOPATRIMONIO_PK PRIMARY KEY (idTipoPatrimonio)
);

CREATE TABLE PATRIMONIO (
    idPatrimonio INT NOT NULL,
    valor FLOAT NOT NULL,
    detalhe VARCHAR(300),
    idTipoPatrimonio INT NOT NULL,
    ano DATE,
    cpf VARCHAR(15) NOT NULL,

    CONSTRAINT PATRIMONIO_PK PRIMARY KEY (idPatrimonio),
    CONSTRAINT PATRIMONIO_TIPOPATRIMONIO_FK FOREIGN KEY (idTipoPatrimonio) REFERENCES TIPOPATRIMONIO (idTipoPatrimonio),
    CONSTRAINT PATRIMONIO_CANDIDATURA_FK FOREIGN KEY (ano, cpf) REFERENCES CANDIDATURA (ano, cpf)
);

CREATE TABLE RESULTADO (
    idResultado INT NOT NULL,
    descricaoResultado VARCHAR(50) NOT NULL,

    CONSTRAINT RESULTADO_PK PRIMARY KEY (idResultado)
);

CREATE TABLE ELEICAO (
    idEleicao INT NOT NULL,
    turno enum('1', '2') NOT NULL,
    idResultado INT NOT NULL,
    ano DATE NOT NULL,
    cpf VARCHAR(15) NOT NULL,

    CONSTRAINT ELEICAO_PK PRIMARY KEY (idEleicao),
    CONSTRAINT ELEICAO_CANDIDATURA_FK FOREIGN KEY (ano, cpf) REFERENCES CANDIDATURA (ano, cpf)
    CONSTRAINT ELEICAO_UK UNIQUE (ano, cpf),
    CONSTRAINT ELEICAO_RESULTADO_FK FOREIGN KEY (idResultado) REFERENCES RESULTADO (idResultado)
);
