--  ----------------------- eleicoes --------------------------
--                                                                  
--                    SCRIPT DE INSERÇÃO (DML)                           
--                                                                  
-- Data Criacao ..........: 02/12/2019                             
-- Autor(es) .............:
--     Rômulo Souza - 15/0147601
--     Vinícius Lima - 15/0151331
-- Banco de Dados ........: MySQL                                   
-- Base de Dados(nome) ...: eleicoes                                                                                      
--                                                                  
-- PROJETO => 1 Base de Dados                                       
--         => 7 Tabelas                                           
--                                                                  
-- -----------------------------------------------------------------

USE eleicoes;

INSERT INTO CARGO (descricaoCargo) VALUES ('GOVERNADOR');
INSERT INTO CARGO (descricaoCargo) VALUES ('DEPUTADO ESTADUAL');
INSERT INTO CARGO (descricaoCargo) VALUES ('2o SUPLENTE SENADOR');
INSERT INTO CARGO (descricaoCargo) VALUES ('VICE-PRESIDENTE');
INSERT INTO CARGO (descricaoCargo) VALUES ('DEPUTADO FEDERAL');
INSERT INTO CARGO (descricaoCargo) VALUES ('DEPUTADO DISTRITAL');
INSERT INTO CARGO (descricaoCargo) VALUES ('VICE-PREFEITO');
INSERT INTO CARGO (descricaoCargo) VALUES ('1o SUPLENTE SENADOR');
INSERT INTO CARGO (descricaoCargo) VALUES ('VICE-GOVERNADOR');
INSERT INTO CARGO (descricaoCargo) VALUES ('PRESIDENTE');
INSERT INTO CARGO (descricaoCargo) VALUES ('VEREADOR');
INSERT INTO CARGO (descricaoCargo) VALUES ('SENADOR');
INSERT INTO CARGO (descricaoCargo) VALUES ('PREFEITO');

INSERT INTO PARTIDO (sigla, nomePartido) VALUES ('PPB', 'PARTIDO PROGRESSISTA BRASILEIRO');
INSERT INTO PARTIDO (sigla, nomePartido) VALUES ('PT', 'PARTIDO DOS TRABALHADORES');
INSERT INTO PARTIDO (sigla, nomePartido) VALUES ('PMDB', 'PARTIDO DO MOVIMENTO DEMOCRATICO BRASILEIRO');
INSERT INTO PARTIDO (sigla, nomePartido) VALUES ('PSDB', 'PARTIDO DA SOCIAL DEMOCRACIA BRASILEIRA');
INSERT INTO PARTIDO (sigla, nomePartido) VALUES ('PFL', 'PARTIDO DA FRENTE LIBERAL');
INSERT INTO PARTIDO (sigla, nomePartido) VALUES ('PC DO B', 'PARTIDO COMUNISTA DO BRASIL');
INSERT INTO PARTIDO (sigla, nomePartido) VALUES ('PSL', 'PARTIDO SOCIAL LIBERAL');
INSERT INTO PARTIDO (sigla, nomePartido) VALUES ('PDT', 'PARTIDO DEMOCRATICO TRABALHISTA');
INSERT INTO PARTIDO (sigla, nomePartido) VALUES ('PMN', 'PARTIDO DA MOBILIZACAO NACIONAL');
INSERT INTO PARTIDO (sigla, nomePartido) VALUES ('PT DO B', 'PARTIDO TRABALHISTA DO BRASIL');
INSERT INTO PARTIDO (sigla, nomePartido) VALUES ('PTB', 'PARTIDO TRABALHISTA BRASILEIRO');
INSERT INTO PARTIDO (sigla, nomePartido) VALUES ('PL', 'PARTIDO LIBERAL');
INSERT INTO PARTIDO (sigla, nomePartido) VALUES ('PSB', 'PARTIDO SOCIALISTA BRASILEIRO');
INSERT INTO PARTIDO (sigla, nomePartido) VALUES ('PV', 'PARTIDO VERDE');
INSERT INTO PARTIDO (sigla, nomePartido) VALUES ('PSD', 'PARTIDO SOCIAL DEMOCRATICO');
INSERT INTO PARTIDO (sigla, nomePartido) VALUES ('PRP', 'PARTIDO REPUBLICANO PROGRESSISTA');
INSERT INTO PARTIDO (sigla, nomePartido) VALUES ('PRN', 'PARTIDO DA RECONSTRUCAO NACIONAL');
INSERT INTO PARTIDO (sigla, nomePartido) VALUES ('PSTU', 'PARTIDO SOCIALISTA DOS TRABALHADORES UNIFICADO');
INSERT INTO PARTIDO (sigla, nomePartido) VALUES ('PST', 'PARTIDO SOCIAL TRABALHISTA');
INSERT INTO PARTIDO (sigla, nomePartido) VALUES ('PSC', 'PARTIDO SOCIAL CRISTAO');
INSERT INTO PARTIDO (sigla, nomePartido) VALUES ('PPS', 'PARTIDO POPULAR SOCIALISTA');
INSERT INTO PARTIDO (sigla, nomePartido) VALUES ('PRTB', 'PARTIDO RENOVADOR TRABALHISTA BRASILEIRO');
INSERT INTO PARTIDO (sigla, nomePartido) VALUES ('PRONA', 'PARTIDO DA REEDIFICACAO DA ORDEM NACIONAL');
INSERT INTO PARTIDO (sigla, nomePartido) VALUES ('PSDC', 'PARTIDO SOCIAL DEMOCRATA CRISTAO');
INSERT INTO PARTIDO (sigla, nomePartido) VALUES ('PAN', 'PARTIDO DOS APOSENTADOS DA NACAO');
INSERT INTO PARTIDO (sigla, nomePartido) VALUES ('PCO', 'PARTIDO DA CAUSA OPERARIA');
INSERT INTO PARTIDO (sigla, nomePartido) VALUES ('PGT', 'PARTIDO GERAL DOS TRABALHADORES');
INSERT INTO PARTIDO (sigla, nomePartido) VALUES ('PCB', 'PARTIDO COMUNISTA BRASILEIRO');
INSERT INTO PARTIDO (sigla, nomePartido) VALUES ('PSN', 'PARTIDO SOLIDARISTA NACIONAL');
INSERT INTO PARTIDO (sigla, nomePartido) VALUES ('PTN', 'PARTIDO TRABALHISTA NACIONAL');
INSERT INTO PARTIDO (sigla, nomePartido) VALUES ('PHS', 'PARTIDO HUMANISTA DA SOLIDARIEDADE');
INSERT INTO PARTIDO (sigla, nomePartido) VALUES ('PTC', 'PARTIDO TRABALHISTA CRISTAO');
INSERT INTO PARTIDO (sigla, nomePartido) VALUES ('PRESTCONTAS', 'PRESTAGCO DE CONTAS - CANDIDATO SEM NZMERO');
INSERT INTO PARTIDO (sigla, nomePartido) VALUES ('PP', 'PARTIDO PROGRESSISTA');
INSERT INTO PARTIDO (sigla, nomePartido) VALUES ('PSOL', 'PARTIDO SOCIALISMO E LIBERDADE');
INSERT INTO PARTIDO (sigla, nomePartido) VALUES ('PRB', 'PARTIDO REPUBLICANO BRASILEIRO');
INSERT INTO PARTIDO (sigla, nomePartido) VALUES ('DEM', 'DEMOCRATAS');
INSERT INTO PARTIDO (sigla, nomePartido) VALUES ('PR', 'PARTIDO DA REPUBLICA');
INSERT INTO PARTIDO (sigla, nomePartido) VALUES ('NAO', 'NAO');
INSERT INTO PARTIDO (sigla, nomePartido) VALUES ('SIM', 'SIM');
INSERT INTO PARTIDO (sigla, nomePartido) VALUES ('PPL', 'PARTIDO PATRIA LIVRE');
INSERT INTO PARTIDO (sigla, nomePartido) VALUES ('SD', 'SOLIDARIEDADE');
INSERT INTO PARTIDO (sigla, nomePartido) VALUES ('PEN', 'PARTIDO ECOLOGICO NACIONAL');
INSERT INTO PARTIDO (sigla, nomePartido) VALUES ('PROS', 'PARTIDO REPUBLICANO DA ORDEM SOCIAL');
INSERT INTO PARTIDO (sigla, nomePartido) VALUES ('PODE', 'PODEMOS');
INSERT INTO PARTIDO (sigla, nomePartido) VALUES ('REDE', 'REDE SUSTENTABILIDADE');
INSERT INTO PARTIDO (sigla, nomePartido) VALUES ('PMB', 'PARTIDO DA MULHER BRASILEIRA');
INSERT INTO PARTIDO (sigla, nomePartido) VALUES ('MDB', 'MOVIMENTO DEMOCRATICO BRASILEIRO');
INSERT INTO PARTIDO (sigla, nomePartido) VALUES ('PATRI', 'PATRIOTA');
INSERT INTO PARTIDO (sigla, nomePartido) VALUES ('DC', 'DEMOCRACIA CRISTA');
INSERT INTO PARTIDO (sigla, nomePartido) VALUES ('NOVO', 'PARTIDO NOVO');
INSERT INTO PARTIDO (sigla, nomePartido) VALUES ('AVANTE', 'AVANTE');
INSERT INTO PARTIDO (sigla, nomePartido) VALUES ('SOLIDARIEDADE', 'SOLIDARIEDADE');

INSERT INTO RESULTADO (descricaoResultado) VALUES ('RENUNCIA;FALECIMENTO;CASSACAO ANTES DA ELEICAO');
INSERT INTO RESULTADO (descricaoResultado) VALUES ('SUPLENTE');
INSERT INTO RESULTADO (descricaoResultado) VALUES ('RENUNCIA/FALECIMENTO/CASSACAO APOS A ELEICAO');
INSERT INTO RESULTADO (descricaoResultado) VALUES ('ELEITO POR MEDIA');
INSERT INTO RESULTADO (descricaoResultado) VALUES ('RENUNCIA;FALECIMENTO;CASSACAO APOS A ELEICAO');
INSERT INTO RESULTADO (descricaoResultado) VALUES ('RENUNCIA/FALECIMENTO COM SUBSTITUICAO');
INSERT INTO RESULTADO (descricaoResultado) VALUES ('SUBSTITUIDO');
INSERT INTO RESULTADO (descricaoResultado) VALUES ('CASSADO COM RECURSO');
INSERT INTO RESULTADO (descricaoResultado) VALUES ('2O TURNO');
INSERT INTO RESULTADO (descricaoResultado) VALUES ('REGISTRO NEGADO ANTES DA ELEICAO');
INSERT INTO RESULTADO (descricaoResultado) VALUES ('ELEITO POR QUOCIENTE PARTIDARIO');
INSERT INTO RESULTADO (descricaoResultado) VALUES ('INDEFERIDO COM RECURSO');
INSERT INTO RESULTADO (descricaoResultado) VALUES ('RENUNCIA/FALECIMENTO/CASSACAO ANTES DA ELEICAO');
INSERT INTO RESULTADO (descricaoResultado) VALUES ('ELEITO POR QP');
INSERT INTO RESULTADO (descricaoResultado) VALUES ('MEDIA');
INSERT INTO RESULTADO (descricaoResultado) VALUES ('REGISTRO NEGADO APOS A ELEICAO');
INSERT INTO RESULTADO (descricaoResultado) VALUES ('NAO ELEITO');
INSERT INTO RESULTADO (descricaoResultado) VALUES ('ELEITO');

INSERT INTO SITUACAO (descricaoSituacao) VALUES ('DEFERIDO COM RECURSO');
INSERT INTO SITUACAO (descricaoSituacao) VALUES ('NAO CONHECIMENTO DO PEDIDO');
INSERT INTO SITUACAO (descricaoSituacao) VALUES ('INAPTO');
INSERT INTO SITUACAO (descricaoSituacao) VALUES ('FALECIDO');
INSERT INTO SITUACAO (descricaoSituacao) VALUES ('CASSADO COM RECURSO');
INSERT INTO SITUACAO (descricaoSituacao) VALUES ('INDEFERIDO COM RECURSO');
INSERT INTO SITUACAO (descricaoSituacao) VALUES ('INDEFERIDO');
INSERT INTO SITUACAO (descricaoSituacao) VALUES ('SUBSTITUTO PENDENTE DE JULGAMENTO');
INSERT INTO SITUACAO (descricaoSituacao) VALUES ('INELEGIVEL');
INSERT INTO SITUACAO (descricaoSituacao) VALUES ('CASSADO');
INSERT INTO SITUACAO (descricaoSituacao) VALUES ('INDEFERIDO POR IMPUGNACAO');
INSERT INTO SITUACAO (descricaoSituacao) VALUES ('CANCELAMENTO');
INSERT INTO SITUACAO (descricaoSituacao) VALUES ('DEFERIDO');
INSERT INTO SITUACAO (descricaoSituacao) VALUES ('SUB JUDICE');
INSERT INTO SITUACAO (descricaoSituacao) VALUES ('RENUNCIA');
INSERT INTO SITUACAO (descricaoSituacao) VALUES ('FALECIMENTO');
INSERT INTO SITUACAO (descricaoSituacao) VALUES ('IMPUGNACAO DE CANDIDATURA');
INSERT INTO SITUACAO (descricaoSituacao) VALUES ('APTO');
INSERT INTO SITUACAO (descricaoSituacao) VALUES ('CANCELADO');
INSERT INTO SITUACAO (descricaoSituacao) VALUES ('SUBSTITUTO MAJORITARIO PENDENTE DE JULGAMENTO');
INSERT INTO SITUACAO (descricaoSituacao) VALUES ('HOMOLOGACAO DE RENUNCIA');
INSERT INTO SITUACAO (descricaoSituacao) VALUES ('CASSACAO DO REGISTRO');
