USE eleicoes;

INSERT INTO SITUACAO (descricaoSituacao) VALUES ('DEFERIDO COM RECURSO');

INSERT INTO SITUACAO (descricaoSituacao) VALUES ('NAO CONHECIMENTO DO PEDIDO');

INSERT INTO SITUACAO (descricaoSituacao) VALUES ('INAPTO');

INSERT INTO SITUACAO (descricaoSituacao) VALUES ('FALECIDO');

INSERT INTO SITUACAO (descricaoSituacao) VALUES ('CASSADO COM RECURSO');

INSERT INTO SITUACAO (descricaoSituacao) VALUES ('INDEFERIDO COM RECURSO');

INSERT INTO SITUACAO (descricaoSituacao) VALUES ('INDEFERIDO');

INSERT INTO SITUACAO (descricaoSituacao) VALUES ('SUBSTITUTO PENDENTE DE JULGAMENTO');

INSERT INTO SITUACAO (descricaoSituacao) VALUES ('INELEGIVEL');

INSERT INTO SITUACAO (descricaoSituacao) VALUES ('CASSADO');

INSERT INTO SITUACAO (descricaoSituacao) VALUES ('INDEFERIDO POR IMPUGNACAO');

INSERT INTO SITUACAO (descricaoSituacao) VALUES ('CANCELAMENTO');

INSERT INTO SITUACAO (descricaoSituacao) VALUES ('DEFERIDO');

INSERT INTO SITUACAO (descricaoSituacao) VALUES ('SUB JUDICE');

INSERT INTO SITUACAO (descricaoSituacao) VALUES ('RENUNCIA');

INSERT INTO SITUACAO (descricaoSituacao) VALUES ('FALECIMENTO');

INSERT INTO SITUACAO (descricaoSituacao) VALUES ('IMPUGNACAO DE CANDIDATURA');

INSERT INTO SITUACAO (descricaoSituacao) VALUES ('APTO');

INSERT INTO SITUACAO (descricaoSituacao) VALUES ('CANCELADO');

INSERT INTO SITUACAO (descricaoSituacao) VALUES ('SUBSTITUTO MAJORITARIO PENDENTE DE JULGAMENTO');

INSERT INTO SITUACAO (descricaoSituacao) VALUES ('HOMOLOGACAO DE RENUNCIA');

INSERT INTO SITUACAO (descricaoSituacao) VALUES ('CASSACAO DO REGISTRO');
