USE eleicoes;

INSERT INTO PARTIDO (sigla, nomePartido)
VALUES ('PPB', 'PARTIDO PROGRESSISTA BRASILEIRO');

INSERT INTO PARTIDO (sigla, nomePartido)
VALUES ('PT', 'PARTIDO DOS TRABALHADORES');

INSERT INTO PARTIDO (sigla, nomePartido)
VALUES ('PMDB', 'PARTIDO DO MOVIMENTO DEMOCRATICO BRASILEIRO');

INSERT INTO PARTIDO (sigla, nomePartido)
VALUES ('PSDB', 'PARTIDO DA SOCIAL DEMOCRACIA BRASILEIRA');

INSERT INTO PARTIDO (sigla, nomePartido)
VALUES ('PFL', 'PARTIDO DA FRENTE LIBERAL');

INSERT INTO PARTIDO (sigla, nomePartido)
VALUES ('PC DO B', 'PARTIDO COMUNISTA DO BRASIL');

INSERT INTO PARTIDO (sigla, nomePartido)
VALUES ('PSL', 'PARTIDO SOCIAL LIBERAL');

INSERT INTO PARTIDO (sigla, nomePartido)
VALUES ('PDT', 'PARTIDO DEMOCRATICO TRABALHISTA');

INSERT INTO PARTIDO (sigla, nomePartido)
VALUES ('PMN', 'PARTIDO DA MOBILIZACAO NACIONAL');

INSERT INTO PARTIDO (sigla, nomePartido)
VALUES ('PT DO B', 'PARTIDO TRABALHISTA DO BRASIL');

INSERT INTO PARTIDO (sigla, nomePartido)
VALUES ('PTB', 'PARTIDO TRABALHISTA BRASILEIRO');

INSERT INTO PARTIDO (sigla, nomePartido)
VALUES ('PL', 'PARTIDO LIBERAL');

INSERT INTO PARTIDO (sigla, nomePartido)
VALUES ('PSB', 'PARTIDO SOCIALISTA BRASILEIRO');

INSERT INTO PARTIDO (sigla, nomePartido)
VALUES ('PV', 'PARTIDO VERDE');

INSERT INTO PARTIDO (sigla, nomePartido)
VALUES ('PSD', 'PARTIDO SOCIAL DEMOCRATICO');

INSERT INTO PARTIDO (sigla, nomePartido)
VALUES ('PRP', 'PARTIDO REPUBLICANO PROGRESSISTA');

INSERT INTO PARTIDO (sigla, nomePartido)
VALUES ('PRN', 'PARTIDO DA RECONSTRUCAO NACIONAL');

INSERT INTO PARTIDO (sigla, nomePartido)
VALUES ('PSTU', 'PARTIDO SOCIALISTA DOS TRABALHADORES UNIFICADO');

INSERT INTO PARTIDO (sigla, nomePartido)
VALUES ('PST', 'PARTIDO SOCIAL TRABALHISTA');

INSERT INTO PARTIDO (sigla, nomePartido)
VALUES ('PSC', 'PARTIDO SOCIAL CRISTAO');

INSERT INTO PARTIDO (sigla, nomePartido)
VALUES ('PPS', 'PARTIDO POPULAR SOCIALISTA');

INSERT INTO PARTIDO (sigla, nomePartido)
VALUES ('PRTB', 'PARTIDO RENOVADOR TRABALHISTA BRASILEIRO');

INSERT INTO PARTIDO (sigla, nomePartido)
VALUES ('PRONA', 'PARTIDO DA REEDIFICACAO DA ORDEM NACIONAL');

INSERT INTO PARTIDO (sigla, nomePartido)
VALUES ('PSDC', 'PARTIDO SOCIAL DEMOCRATA CRISTAO');

INSERT INTO PARTIDO (sigla, nomePartido)
VALUES ('PAN', 'PARTIDO DOS APOSENTADOS DA NACAO');

INSERT INTO PARTIDO (sigla, nomePartido)
VALUES ('PCO', 'PARTIDO DA CAUSA OPERARIA');

INSERT INTO PARTIDO (sigla, nomePartido)
VALUES ('PGT', 'PARTIDO GERAL DOS TRABALHADORES');

INSERT INTO PARTIDO (sigla, nomePartido)
VALUES ('PCB', 'PARTIDO COMUNISTA BRASILEIRO');

INSERT INTO PARTIDO (sigla, nomePartido)
VALUES ('PSN', 'PARTIDO SOLIDARISTA NACIONAL');

INSERT INTO PARTIDO (sigla, nomePartido)
VALUES ('PTN', 'PARTIDO TRABALHISTA NACIONAL');

INSERT INTO PARTIDO (sigla, nomePartido)
VALUES ('PSN', 'PARTIDO DA SOLIDARIEDADE NACIONAL');

INSERT INTO PARTIDO (sigla, nomePartido)
VALUES ('PHS', 'PARTIDO HUMANISTA DA SOLIDARIEDADE');

INSERT INTO PARTIDO (sigla, nomePartido)
VALUES ('PTC', 'PARTIDO TRABALHISTA CRISTAO');

INSERT INTO PARTIDO (sigla, nomePartido)
VALUES ('PRESTCONTAS', 'PRESTAGCO DE CONTAS - CANDIDATO SEM NZMERO');

INSERT INTO PARTIDO (sigla, nomePartido)
VALUES ('PP', 'PARTIDO PROGRESSISTA');

INSERT INTO PARTIDO (sigla, nomePartido)
VALUES ('PRONA', 'PARTIDO DE REEDIFICACAO DA ORDEM NACIONAL');

INSERT INTO PARTIDO (sigla, nomePartido)
VALUES ('PSOL', 'PARTIDO SOCIALISMO E LIBERDADE');

INSERT INTO PARTIDO (sigla, nomePartido)
VALUES ('PRB', 'PARTIDO REPUBLICANO BRASILEIRO');

INSERT INTO PARTIDO (sigla, nomePartido)
VALUES ('DEM', 'DEMOCRATAS');

INSERT INTO PARTIDO (sigla, nomePartido)
VALUES ('PR', 'PARTIDO DA REPUBLICA');

INSERT INTO PARTIDO (sigla, nomePartido)
VALUES ('NAO', 'NAO');

INSERT INTO PARTIDO (sigla, nomePartido)
VALUES ('SIM', 'SIM');

INSERT INTO PARTIDO (sigla, nomePartido)
VALUES ('PPL', 'PARTIDO PATRIA LIVRE');

INSERT INTO PARTIDO (sigla, nomePartido)
VALUES ('SD', 'SOLIDARIEDADE');

INSERT INTO PARTIDO (sigla, nomePartido)
VALUES ('PEN', 'PARTIDO ECOLOGICO NACIONAL');

INSERT INTO PARTIDO (sigla, nomePartido)
VALUES ('PROS', 'PARTIDO REPUBLICANO DA ORDEM SOCIAL');

INSERT INTO PARTIDO (sigla, nomePartido)
VALUES ('PODE', 'PODEMOS');

INSERT INTO PARTIDO (sigla, nomePartido)
VALUES ('REDE', 'REDE SUSTENTABILIDADE');

INSERT INTO PARTIDO (sigla, nomePartido)
VALUES ('PMB', 'PARTIDO DA MULHER BRASILEIRA');

INSERT INTO PARTIDO (sigla, nomePartido)
VALUES ('MDB', 'MOVIMENTO DEMOCRATICO BRASILEIRO');

INSERT INTO PARTIDO (sigla, nomePartido)
VALUES ('PATRI', 'PATRIOTA');

INSERT INTO PARTIDO (sigla, nomePartido)
VALUES ('DC', 'DEMOCRACIA CRISTA');

INSERT INTO PARTIDO (sigla, nomePartido)
VALUES ('NOVO', 'PARTIDO NOVO');

INSERT INTO PARTIDO (sigla, nomePartido)
VALUES ('AVANTE', 'AVANTE');

INSERT INTO PARTIDO (sigla, nomePartido)
VALUES ('SOLIDARIEDADE', 'SOLIDARIEDADE');

INSERT INTO PARTIDO (sigla, nomePartido)
VALUES ('PP', 'PROGRESSISTAS');
