USE eleicoes;

INSERT INTO RESULTADO (descricaoResultado) VALUES ('RENUNCIA;FALECIMENTO;CASSACAO ANTES DA ELEICAO');

INSERT INTO RESULTADO (descricaoResultado) VALUES ('SUPLENTE');

INSERT INTO RESULTADO (descricaoResultado) VALUES ('RENUNCIA/FALECIMENTO/CASSACAO APOS A ELEICAO');

INSERT INTO RESULTADO (descricaoResultado) VALUES ('ELEITO POR MEDIA');

INSERT INTO RESULTADO (descricaoResultado) VALUES ('RENUNCIA;FALECIMENTO;CASSACAO APOS A ELEICAO');

INSERT INTO RESULTADO (descricaoResultado) VALUES ('RENUNCIA/FALECIMENTO COM SUBSTITUICAO');

INSERT INTO RESULTADO (descricaoResultado) VALUES ('SUBSTITUIDO');

INSERT INTO RESULTADO (descricaoResultado) VALUES ('CASSADO COM RECURSO');

INSERT INTO RESULTADO (descricaoResultado) VALUES ('2O TURNO');

INSERT INTO RESULTADO (descricaoResultado) VALUES ('REGISTRO NEGADO ANTES DA ELEICAO');

INSERT INTO RESULTADO (descricaoResultado) VALUES ('ELEITO POR QUOCIENTE PARTIDARIO');

INSERT INTO RESULTADO (descricaoResultado) VALUES ('INDEFERIDO COM RECURSO');

INSERT INTO RESULTADO (descricaoResultado) VALUES ('RENUNCIA/FALECIMENTO/CASSACAO ANTES DA ELEICAO');

INSERT INTO RESULTADO (descricaoResultado) VALUES ('ELEITO POR QP');

INSERT INTO RESULTADO (descricaoResultado) VALUES ('MEDIA');

INSERT INTO RESULTADO (descricaoResultado) VALUES ('REGISTRO NEGADO APOS A ELEICAO');

INSERT INTO RESULTADO (descricaoResultado) VALUES ('NAO ELEITO');

INSERT INTO RESULTADO (descricaoResultado) VALUES ('ELEITO');
