USE eleicoes;

INSERT INTO CARGO (descricaoCargo) VALUES ('GOVERNADOR');

INSERT INTO CARGO (descricaoCargo) VALUES ('DEPUTADO ESTADUAL');

INSERT INTO CARGO (descricaoCargo) VALUES ('2o SUPLENTE SENADOR');

INSERT INTO CARGO (descricaoCargo) VALUES ('VICE-PRESIDENTE');

INSERT INTO CARGO (descricaoCargo) VALUES ('DEPUTADO FEDERAL');

INSERT INTO CARGO (descricaoCargo) VALUES ('DEPUTADO DISTRITAL');

INSERT INTO CARGO (descricaoCargo) VALUES ('VICE-PREFEITO');

INSERT INTO CARGO (descricaoCargo) VALUES ('1o SUPLENTE SENADOR');

INSERT INTO CARGO (descricaoCargo) VALUES ('VICE-GOVERNADOR');

INSERT INTO CARGO (descricaoCargo) VALUES ('PRESIDENTE');

INSERT INTO CARGO (descricaoCargo) VALUES ('VEREADOR');

INSERT INTO CARGO (descricaoCargo) VALUES ('SENADOR');

INSERT INTO CARGO (descricaoCargo) VALUES ('PREFEITO');
